package de.codinix.videoeditor.whisper

import java.util.Locale

/**
 * Wörterbuch Wort → Emoji (Deutsch/Englisch). Einträge sind Wortstämme; ein Wort trifft,
 * wenn es (klein geschrieben, ohne Satzzeichen) exakt gleich ist oder mit dem Stamm beginnt.
 * Deterministisch, offline, sofort – bewusst kein Sprachmodell.
 */
object EmojiDict {

    private val entries: Map<String, String> by lazy { build() }
    private val exact: Set<String> by lazy { entries.keys.filter { it.length < 4 }.toSet() }
    private val stems: List<Pair<String, String>> by lazy {
        entries.filter { it.key.length >= 4 }.toList().sortedByDescending { it.first.length }
    }

    fun forWord(word: String): String? {
        val w = word.lowercase(Locale.ROOT).trim().trim('.', ',', '!', '?', ':', ';', '"', '\'', '(', ')', '„', '“')
            .replace("ä", "ae").replace("ö", "oe").replace("ü", "ue").replace("ß", "ss")
        if (w.isEmpty()) return null
        entries[w]?.let { return it }
        if (w in exact) return entries[w]
        for ((stem, emoji) in stems) if (w.startsWith(stem)) return emoji
        return null
    }

    private fun MutableMap<String, String>.add(emoji: String, vararg words: String) {
        words.forEach { this[it.lowercase(Locale.ROOT).replace("ä", "ae").replace("ö", "oe").replace("ü", "ue").replace("ß", "ss")] = emoji }
    }

    private fun build(): Map<String, String> {
        val m = LinkedHashMap<String, String>()
        // Länder & Regionen
        m.add("🇩🇪", "deutschland", "germany", "deutsch", "german")
        m.add("🇦🇹", "oesterreich", "austria")
        m.add("🇨🇭", "schweiz", "switzerland")
        m.add("🇹🇷", "tuerkei", "turkey", "tuerkisch", "turkish", "istanbul", "ankara")
        m.add("🇮🇷", "iran", "iranisch", "iranian", "teheran", "tehran")
        m.add("🇺🇸", "amerika", "america", "usa", "amerikan", "american", "washington", "trump")
        m.add("🇷🇺", "russland", "russia", "russisch", "russian", "moskau", "moscow", "putin")
        m.add("🇺🇦", "ukraine", "ukrain", "kiew", "kyiv")
        m.add("🇫🇷", "frankreich", "france", "franzoes", "french", "paris")
        m.add("🇬🇧", "england", "britannien", "britain", "london", "britisch", "british")
        m.add("🇮🇹", "italien", "italy", "italienisch", "italian", "rom", "rome")
        m.add("🇪🇸", "spanien", "spain", "spanisch", "spanish", "madrid")
        m.add("🇨🇳", "china", "chines", "peking", "beijing")
        m.add("🇯🇵", "japan", "japanisch", "japanese", "tokio", "tokyo")
        m.add("🇮🇳", "indien", "india", "indisch", "indian")
        m.add("🇧🇷", "brasilien", "brazil")
        m.add("🇸🇦", "saudi", "riad", "riyadh")
        m.add("🇮🇱", "israel", "israelisch", "israeli")
        m.add("🇵🇸", "palaestina", "palestine", "gaza")
        m.add("🇸🇾", "syrien", "syria")
        m.add("🇮🇶", "irak", "iraq")
        m.add("🇦🇫", "afghanistan")
        m.add("🇵🇰", "pakistan")
        m.add("🇬🇷", "griechenland", "greece")
        m.add("🇵🇱", "polen", "poland")
        m.add("🇳🇱", "niederlande", "holland", "netherlands")
        m.add("🇲🇦", "marokko", "morocco")
        m.add("🇪🇬", "aegypten", "egypt")
        m.add("🇲🇽", "mexiko", "mexico")
        m.add("🇨🇦", "kanada", "canada")
        m.add("🇦🇺", "australien", "australia")
        m.add("🇰🇷", "korea", "seoul")
        m.add("🇪🇺", "europa", "europe", "eu")
        m.add("🌍", "welt", "world", "erde", "earth", "planet", "global")
        // Konflikt, Politik, Nachrichten
        m.add("💥", "explosion", "explodier", "explode", "detonation", "knall", "bombe", "bomb")
        m.add("🔥", "feuer", "fire", "brand", "brenn", "flamme", "flame", "heiss", "hot")
        m.add("🚀", "rakete", "rocket", "missile", "start", "launch")
        m.add("✈️", "flugzeug", "airplane", "plane", "flug", "flight", "flieg", "fly")
        m.add("🪖", "soldat", "soldier", "armee", "army", "militaer", "military")
        m.add("⚔️", "krieg", "war", "kampf", "fight", "schlacht", "battle", "angriff", "attack")
        m.add("🕊️", "frieden", "peace", "waffenruhe", "ceasefire")
        m.add("🗳️", "wahl", "election", "vote", "abstimm")
        m.add("🏛️", "regierung", "government", "parlament", "parliament", "bundestag", "kongress", "congress")
        m.add("👑", "koenig", "king", "queen", "koenigin", "kronprinz", "prince")
        m.add("📰", "nachricht", "news", "zeitung", "newspaper", "schlagzeile", "headline")
        m.add("🎤", "interview", "rede", "speech", "mikrofon", "microphone")
        m.add("🚨", "alarm", "polizei", "police", "notfall", "emergency")
        m.add("⚖️", "gericht", "court", "gesetz", "law", "urteil", "verdict", "richter", "judge")
        m.add("🔒", "sicherheit", "security", "geheim", "secret")
        // Geld & Wirtschaft
        m.add("💰", "geld", "money", "cash", "reich", "rich", "vermoegen", "wealth")
        m.add("💶", "euro")
        m.add("💵", "dollar")
        m.add("📈", "aktie", "stock", "boerse", "market", "gewinn", "profit", "wachstum", "growth", "steig")
        m.add("📉", "verlust", "loss", "crash", "krise", "crisis", "fall", "sink", "rezession")
        m.add("🏦", "bank", "kredit", "credit", "zins", "interest")
        m.add("₿", "bitcoin", "crypto", "krypto")
        m.add("🛒", "kauf", "buy", "shopping", "einkauf", "supermarkt")
        m.add("💳", "karte", "card", "bezahl", "payment", "zahlung")
        m.add("🏢", "firma", "company", "unternehmen", "business", "konzern")
        m.add("💼", "job", "arbeit", "work", "beruf", "career", "karriere")
        // Technik
        m.add("📱", "handy", "phone", "smartphone", "iphone", "telefon")
        m.add("💻", "computer", "laptop", "pc", "rechner")
        m.add("🤖", "roboter", "robot", "ki", "ai", "kuenstliche", "artificial", "chatgpt")
        m.add("🌐", "internet", "online", "web", "netz", "network")
        m.add("📸", "foto", "photo", "kamera", "camera", "bild", "picture")
        m.add("🎥", "video", "film", "movie", "kino", "cinema")
        m.add("🎵", "musik", "music", "song", "lied", "melodie")
        m.add("🎮", "spiel", "game", "gaming", "zock")
        m.add("⚡", "strom", "electric", "energie", "energy", "blitz", "lightning", "schnell", "fast")
        m.add("🔋", "batterie", "battery", "akku")
        m.add("🚗", "auto", "car", "wagen", "fahrzeug", "vehicle", "fahr", "drive")
        m.add("🚌", "bus")
        m.add("🚆", "zug", "train", "bahn", "railway")
        m.add("🚲", "fahrrad", "bike", "bicycle", "rad")
        m.add("🏠", "haus", "house", "zuhause", "home", "wohnung", "apartment")
        m.add("🏙️", "stadt", "city", "downtown")
        // Wetter & Natur
        m.add("☀️", "sonne", "sun", "sonnig", "sunny", "sommer", "summer")
        m.add("🌧️", "regen", "rain", "regne")
        m.add("❄️", "schnee", "snow", "winter", "kalt", "cold", "eis", "ice", "frost")
        m.add("⛈️", "sturm", "storm", "gewitter", "thunder", "unwetter", "hurricane", "orkan")
        m.add("🌊", "meer", "sea", "ocean", "ozean", "welle", "wave", "strand", "beach")
        m.add("🌳", "baum", "tree", "wald", "forest", "natur", "nature")
        m.add("🏔️", "berg", "mountain", "gipfel", "alpen")
        m.add("🌸", "blume", "flower", "fruehling", "spring")
        m.add("🍂", "herbst", "autumn", "fall")
        m.add("🌙", "mond", "moon", "nacht", "night")
        m.add("⭐", "stern", "star", "sterne")
        m.add("🌈", "regenbogen", "rainbow")
        m.add("🐶", "hund", "dog", "welpe", "puppy")
        m.add("🐱", "katze", "cat", "kater", "kitten")
        m.add("🐴", "pferd", "horse")
        m.add("🐟", "fisch", "fish")
        m.add("🐦", "vogel", "bird")
        m.add("🦁", "loewe", "lion")
        m.add("🐻", "baer", "bear")
        m.add("🐘", "elefant", "elephant")
        m.add("🐝", "biene", "bee")
        // Essen & Trinken
        m.add("🍕", "pizza")
        m.add("🍔", "burger", "hamburger")
        m.add("🍟", "pommes", "fries")
        m.add("🌯", "doener", "kebab", "duerum", "wrap")
        m.add("🍞", "brot", "bread", "broetchen")
        m.add("🍰", "kuchen", "cake", "torte", "dessert")
        m.add("🍫", "schokolade", "chocolate", "schoko")
        m.add("🍎", "apfel", "apple", "obst", "fruit")
        m.add("🥗", "salat", "salad", "gemuese", "vegetable", "vegan", "gesund", "healthy")
        m.add("🍗", "fleisch", "meat", "huhn", "chicken", "haehnchen")
        m.add("☕", "kaffee", "coffee", "cappuccino", "espresso")
        m.add("🍵", "tee", "tea", "chai")
        m.add("🍺", "bier", "beer")
        m.add("🍷", "wein", "wine")
        m.add("💧", "wasser", "water", "durst", "thirsty")
        m.add("🍽️", "essen", "food", "eat", "mahlzeit", "restaurant", "dinner", "lunch", "fruehstueck", "breakfast", "hunger", "hungrig", "hungry", "koch", "cook")
        // Gefühle & Menschen
        m.add("❤️", "liebe", "love", "herz", "heart", "lieb", "verliebt")
        m.add("😂", "lach", "laugh", "lustig", "funny", "witz", "joke", "haha", "lol")
        m.add("😢", "trauer", "sad", "traurig", "wein", "cry", "traene", "tears")
        m.add("😡", "wut", "angry", "wuetend", "zorn", "sauer", "hass", "hate", "aerger")
        m.add("😱", "angst", "fear", "scary", "schock", "shock", "panik", "panic", "horror")
        m.add("😍", "wunderschoen", "beautiful", "traumhaft", "gorgeous")
        m.add("😎", "cool", "laessig", "chill")
        m.add("🤔", "frage", "question", "warum", "why", "ueberleg", "think", "nachdenk", "wieso")
        m.add("😴", "schlaf", "sleep", "muede", "tired", "bett", "bed")
        m.add("🎉", "party", "feier", "celebrat", "fest", "festival", "jubel")
        m.add("🎂", "geburtstag", "birthday")
        m.add("🎄", "weihnacht", "christmas")
        m.add("👶", "baby", "kind", "child", "kinder", "children")
        m.add("👨‍👩‍👧", "familie", "family", "eltern", "parents")
        m.add("👫", "freund", "friend", "kumpel", "buddy", "partner")
        m.add("💍", "hochzeit", "wedding", "heirat", "marry", "ehe", "marriage")
        m.add("🙏", "danke", "thank", "bitte", "please", "gebet", "pray", "hoffe", "hope")
        m.add("👍", "gut", "good", "super", "great", "toll", "geil", "perfekt", "perfect", "okay", "ok", "richtig", "right")
        m.add("👎", "schlecht", "bad", "falsch", "wrong", "schrecklich", "terrible", "furchtbar", "awful")
        m.add("💪", "stark", "strong", "kraft", "power", "muskel", "muscle", "training", "gym", "sport")
        m.add("🧠", "gehirn", "brain", "denken", "idee", "idea", "klug", "smart", "intelligen")
        m.add("👀", "schau", "look", "seh", "see", "watch", "augen", "eyes", "guck")
        m.add("👂", "hoer", "hear", "listen", "ohr", "ear")
        m.add("🗣️", "sag", "say", "sprech", "speak", "talk", "red", "erzaehl", "tell")
        m.add("✍️", "schreib", "write", "text", "brief", "letter")
        m.add("📚", "buch", "book", "lern", "learn", "schule", "school", "studi", "study", "uni", "university", "lesen", "read")
        m.add("🎓", "abschluss", "graduat", "pruefung", "exam", "diplom")
        m.add("🏥", "krankenhaus", "hospital", "arzt", "doctor", "krank", "sick", "medizin", "medicine", "gesundheit", "health")
        m.add("💊", "tablette", "pill", "medikament", "drug")
        m.add("🦠", "virus", "corona", "covid", "pandemie", "pandemic")
        m.add("⚽", "fussball", "football", "soccer", "tor", "goal", "bundesliga", "champions")
        m.add("🏀", "basketball", "nba")
        m.add("🎾", "tennis")
        m.add("🏆", "gewinn", "win", "sieg", "victory", "champion", "meister", "pokal", "trophy", "erster", "first")
        m.add("🏃", "lauf", "run", "jogg", "marathon", "rennen", "race")
        m.add("🏊", "schwimm", "swim")
        m.add("⏰", "zeit", "time", "uhr", "clock", "spaet", "late", "frueh", "early", "minute", "stunde", "hour")
        m.add("📅", "termin", "appointment", "datum", "date", "kalender", "calendar", "montag", "monday", "wochenende", "weekend", "morgen", "tomorrow", "heute", "today")
        m.add("✅", "fertig", "done", "erledigt", "geschafft", "ja", "yes", "stimmt", "klar", "genau", "exactly", "richtig")
        m.add("❌", "nein", "no", "nicht", "not", "never", "niemals", "verboten", "stop", "stopp")
        m.add("⚠️", "achtung", "warning", "vorsicht", "careful", "gefahr", "danger", "wichtig", "important")
        m.add("💡", "tipp", "tip", "trick", "loesung", "solution", "erklaer", "explain")
        m.add("🎯", "ziel", "goal", "target", "fokus", "focus", "plan")
        m.add("🔑", "schluessel", "key", "wichtigste", "loesung")
        m.add("🎁", "geschenk", "gift", "present", "ueberraschung", "surprise")
        m.add("✨", "magie", "magic", "zauber", "wunder", "amazing", "unglaublich", "incredible", "wow", "krass")
        m.add("💯", "hundert", "hundred", "prozent", "percent", "komplett", "voll", "total")
        m.add("🤝", "deal", "vertrag", "contract", "einig", "agree", "zusammen", "together", "team")
        m.add("📍", "ort", "place", "hier", "here", "wo", "where", "standort", "location")
        m.add("🗺️", "reise", "travel", "trip", "urlaub", "vacation", "holiday", "tour")
        m.add("🏝️", "insel", "island", "paradies", "paradise")
        m.add("🛫", "flughafen", "airport", "abflug")
        m.add("🚢", "schiff", "ship", "boot", "boat", "kreuzfahrt", "cruise")
        m.add("🏨", "hotel")
        m.add("🎬", "dreh", "shoot", "szene", "scene", "action", "regie")
        m.add("📺", "fernseh", "tv", "television", "serie", "series", "netflix", "youtube", "tiktok", "instagram")
        m.add("🔔", "abonnier", "subscribe", "follow", "folg", "glocke", "bell")
        m.add("👋", "hallo", "hello", "hi", "hey", "servus", "moin", "tschuess", "bye", "willkommen", "welcome")
        return m
    }
}
